using System;
using System.Collections.Generic;
using System.Linq;
namespace PoopDetector.AI;

public static class YoloXColormap
{
    public static List<(string, System.Drawing.Color)> ColormapList => [
                new ("person", System.Drawing.Color.White),
        new ("bicycle", System.Drawing.Color.Red),
        new ("car", System.Drawing.Color.Yellow),
        new ("motorcycle", System.Drawing.Color.Aqua),
        new ("airplane", System.Drawing.Color.Gray),
        new ("bus", System.Drawing.Color.Green),
        new ("train", System.Drawing.Color.GreenYellow),
        new ("truck", System.Drawing.Color.Brown),
        new ("boat", System.Drawing.Color.RosyBrown),
        new ("traffic light", System.Drawing.Color.Orange),
        new ("fire hydrant", System.Drawing.Color.BlueViolet),
        new ("stop sign", System.Drawing.Color.LawnGreen),
        new ("parking meter", System.Drawing.Color.Black),
        new ("bench", System.Drawing.Color.ForestGreen),
        new ("bird", System.Drawing.Color.Yellow),
        new ("cat", System.Drawing.Color.LightPink),
        new ("dog", System.Drawing.Color.Blue),
        new ("horse", System.Drawing.Color.LightGreen),
        new ("sheep", System.Drawing.Color.DarkSlateBlue),
        new ("cow", System.Drawing.Color.CornflowerBlue),
        new ("elephant", System.Drawing.Color.Aqua),
        new ("bear", System.Drawing.Color.Aqua),
        new ("zebra", System.Drawing.Color.Aqua),
        new ("giraffe", System.Drawing.Color.Aqua),
        new ("backpack", System.Drawing.Color.Yellow),
        new ("umbrella", System.Drawing.Color.DarkSalmon),
        new ("handbag", System.Drawing.Color.Aqua),
        new ("tie", System.Drawing.Color.Bisque),
        new ("suitcase", System.Drawing.Color.Aqua),
        new ("frisbee", System.Drawing.Color.Aqua),
        new ("skis", System.Drawing.Color.Chocolate),
        new ("snowboard", System.Drawing.Color.Coral),
        new ("sports ball", System.Drawing.Color.Cornsilk),
        new ("kite", System.Drawing.Color.MintCream),
        new ("baseball bat", System.Drawing.Color.LightCoral),
        new ("baseball glove", System.Drawing.Color.DarkCyan),
        new ("skateboard", System.Drawing.Color.Cyan),
        new ("surfboard", System.Drawing.Color.Crimson),
        new ("tennis racket", System.Drawing.Color.Chartreuse),
        new ("bottle", System.Drawing.Color.CadetBlue),
        new ("wine glass", System.Drawing.Color.Tan),
        new ("cup", System.Drawing.Color.Brown),
        new ("fork", System.Drawing.Color.BurlyWood),
        new ("knife", System.Drawing.Color.MediumVioletRed),
        new ("spoon", System.Drawing.Color.Aqua),
        new ("bowl", System.Drawing.Color.Aqua),
        new ("banana", System.Drawing.Color.Aqua),
        new ("apple", System.Drawing.Color.Aqua),
        new ("sandwich", System.Drawing.Color.Wheat),
        new ("orange", System.Drawing.Color.Khaki),
        new ("broccoli", System.Drawing.Color.Tomato),
        new ("carrot", System.Drawing.Color.Turquoise),
        new ("hot dog", System.Drawing.Color.Peru),
        new ("pizza", System.Drawing.Color.PeachPuff),
        new ("donut", System.Drawing.Color.PapayaWhip),
        new ("cake", System.Drawing.Color.LightCoral),
        new ("chair", System.Drawing.Color.Aquamarine),
        new ("couch", System.Drawing.Color.DarkViolet),
        new ("potted plant", System.Drawing.Color.Bisque),
        new ("bed", System.Drawing.Color.Goldenrod),
        new ("dining table", System.Drawing.Color.HotPink),
        new ("toilet", System.Drawing.Color.Honeydew),
        new ("tv", System.Drawing.Color.PaleVioletRed),
        new ("laptop", System.Drawing.Color.IndianRed),
        new ("mouse", System.Drawing.Color.Aqua),
        new ("remote", System.Drawing.Color.BlueViolet),
        new ("keyboard", System.Drawing.Color.DarkOrange),
        new ("cell phone", System.Drawing.Color.OrangeRed),
        new ("microwave", System.Drawing.Color.WhiteSmoke),
        new ("oven", System.Drawing.Color.LightYellow),
        new ("toaster", System.Drawing.Color.Aqua),
        new ("sink", System.Drawing.Color.Aqua),
        new ("refrigerator", System.Drawing.Color.Aqua),
        new ("book", System.Drawing.Color.LightSlateGray),
        new ("clock", System.Drawing.Color.Teal),
        new ("vase", System.Drawing.Color.Thistle),
        new ("scissors", System.Drawing.Color.Orchid),
        new ("teddy bear", System.Drawing.Color.OldLace),
        new ("hair drier", System.Drawing.Color.Olive),
        new ("toothbrush", System.Drawing.Color.Aqua)];

    public static List<(string, System.Drawing.Color)> PoopList = [new("poop", System.Drawing.Color.Red)];
}
